"""Add MRI image columns to Patient

Revision ID: 3a1f508d081b
Revises: 14e74170e3e9
Create Date: 2024-05-28 04:14:27.265716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a1f508d081b'
down_revision = '14e74170e3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glioma_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meningioma_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pituitary_image', sa.String(length=200), nullable=True))
        batch_op.drop_column('mri_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mri_image', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('pituitary_image')
        batch_op.drop_column('meningioma_image')
        batch_op.drop_column('glioma_image')

    # ### end Alembic commands ###
