"""Added scanned_image_path and detection_report to Patient model

Revision ID: 3abc3e59217e
Revises: 5527676ae2f6
Create Date: 2024-07-21 08:18:02.239774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abc3e59217e'
down_revision = '5527676ae2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_image_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('detection_report', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('detection_report')
        batch_op.drop_column('scanned_image_path')

    # ### end Alembic commands ###
