"""Add contact_number and date_added to Patient

Revision ID: 44b8f65ff79c
Revises: da40d6a1e9d7
Create Date: 2024-05-25 01:38:03.261913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b8f65ff79c'
down_revision = 'da40d6a1e9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('date_added')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
