"""Update Patient table with ON DELETE SET NULL for specialist_id

Revision ID: 5527676ae2f6
Revises: 78d57f4330c3
Create Date: 2024-07-18 04:23:45.747587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5527676ae2f6'
down_revision = '78d57f4330c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialist_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialist_last_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('specialist_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('patient_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_ibfk_1', 'specialist', ['specialist_id'], ['id'])
        batch_op.alter_column('specialist_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('specialist_last_name')
        batch_op.drop_column('specialist_first_name')

    # ### end Alembic commands ###
