"""Add patient_ic and patient_id to Patient

Revision ID: da40d6a1e9d7
Revises: 0bc99b18be06
Create Date: 2024-05-23 23:53:31.374830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da40d6a1e9d7'
down_revision = '0bc99b18be06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_ic', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patient_id')
        batch_op.drop_column('patient_ic')

    # ### end Alembic commands ###
